import { AppProps } from "next/app";
import "../styles/globals.css";
import Head from "next/head";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import { DefaultSeo } from "next-seo";
import SEO from "@/next-seo.config";

export const metadata = {
  title: "Movie App",
  description: "Generated by create next app",
  icons:
    "https://imgs.search.brave.com/xaW0Db2L0DdIhCGKexlVwBSYLS1uX2m-OQm9ifg4yEM/rs:fit:980:856:1/g:ce/aHR0cDovL2Nkbi5v/bmxpbmV3ZWJmb250/cy5jb20vc3ZnL2lt/Z181MDMzNTgucG5n",
};

const App = ({ Component, pageProps }: AppProps) => {
  return (
    <>
      <DefaultSeo {...SEO} />
      <Head>
        <link rel="shortcut icon" href="/logo.png" type="image/x-icon" />
      </Head>
      <Navbar />
      <Component {...pageProps} />
      <Footer />
    </>
  );
};

export default App;
